name = "my-world-map-coordinates"
main = "worker/index.js"
compatibility_date = "2025-04-01"

# 静态文件托管
assets = { directory = "./dist", not_found_handling = "single-page-application" }

# D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "mc-coords"
database_id = "your-database-id-here"
